-record(serverstate, { channels=[], listeners=[], messages=[] }).
-record(channel, { pid, name }).
-record(state, { listeners=[], messages=[] }).
-record(user, { username, pid }).
-record(message, { username, text }).
